### ISSUE TITLE
Ains is missing his second skill

### ISSUE THREAD

**Issue by sebeiron** [EpicSevenDB/api#15]
Fetching Ains details via the hero api https://api.epicsevendb.com/hero/c3093

His second skill ("Gash", Passive) is not listed.

**Comment by RaphaelDDL** [comment]
Two issues here: 

- The source data is missing the skill enhancements

Created https://github.com/EpicSevenDB/gamedatabase/issues/257

- mongo lookup fails

Because I don't test for array length before doing the $lookup, it fails and the skill is not returned by mongo, so api just sends two skills. Fixing the data source will fix it but I'll also study one how test for length before trying a lookup to avoid these issues in future
